const Clases = ["Base Form", "Past Simple", "Past Participle", "Meaning"];

const Verbos = [
    [ ["be"], ["was", "were"], ["been"], ["ser", "estar"] ],
    [ ["beat"], ["beat"], ["beaten"], ["golpear"] ],
    [ ["become"], ["became"], ["become"], ["llegar a ser", "convertirse"] ],
    [ ["begin"], ["began"], ["begun"], ["empezar"] ],
    [ ["bend"], ["bent"], ["bent"], ["doblar(se)"] ],
    [ ["bet"], ["bet"], ["bet"], ["apostar"] ],
    [ ["bite"], ["bit"], ["bitten"], ["morder"] ],
    [ ["bleed"], ["bled"], ["bled"], ["sangrar"] ],
    [ ["blow"], ["blew"], ["blown"], ["soplar"] ],
    [ ["break"], ["broke"], ["broken"], ["romper"] ],
    [ ["bring"], ["brought"], ["brought"], ["traer"] ],
    [ ["build"], ["built"], ["built"], ["construir"] ],
    [ ["burn"], ["burnt", "burned"], ["burnt", "burned"], ["quemar"] ],
    [ ["buy"], ["bought"], ["bought"], ["comprar"] ],
    [ ["catch"], ["caught"], ["caught"], ["coger", "agarrar"] ],
    [ ["choose"], ["chose"], ["chosen"], ["elegir"] ],
    [ ["come"], ["came"], ["come"], ["venir"] ],
    [ ["cost"], ["cost"], ["cost"], ["costar"] ],
    [ ["cut"], ["cut"], ["cut"], ["cortar"] ],
    [ ["dig"], ["dug"], ["dug"], ["cavar"] ],
    [ ["do"], ["did"], ["done"], ["hacer"] ],
    [ ["draw"], ["drew"], ["drawn"], ["dibujar"] ],
    [ ["dream"], ["dreamt", "dreamed"], ["dreamt", "dreamed"], ["soñar"] ],
    [ ["drink"], ["drank"], ["drunk"], ["beber"] ],
    [ ["drive"], ["drove"], ["driven"], ["conducir"] ],
    [ ["eat"], ["ate"], ["eaten"], ["comer"] ],
    [ ["fall"], ["fell"], ["fallen"], ["caer(se)"] ],
    [ ["feed"], ["fed"], ["fed"], ["alimentar"] ],
    [ ["feel"], ["felt"], ["felt"], ["sentir(se)"] ],
    [ ["fight"], ["fought"], ["fought"], ["luchar", "pelear"] ],
    [ ["find"], ["found"], ["found"], ["encontrar"] ],
    [ ["fly"], ["flew"], ["flown"], ["volar"] ],
    [ ["forget"], ["forgot"], ["forgotten"], ["olvidar"] ],
    [ ["forgive"], ["forgave"], ["forgiven"], ["perdonar"] ],
    [ ["freeze"], ["froze"], ["frozen"], ["congelar(se)"] ],
    [ ["get"], ["got"], ["got"], ["conseguir", "llegar"] ],
    [ ["give"], ["gave"], ["given"], ["dar"] ],
    [ ["go"], ["went"], ["gone"], ["ir"] ],
    [ ["grow"], ["grew"], ["grown"], ["crecer", "cultivar"] ],
    [ ["hang"], ["hanged", "hung"], ["hanged", "hung"], ["colgar"] ],
    [ ["have"], ["had"], ["had"], ["tener", "haber"] ],
    [ ["hear"], ["heard"], ["heard"], ["oir"] ],
    [ ["hide"], ["hid"], ["hidden"], ["esconder(se)"] ],
    [ ["hit"], ["hit"], ["hit"], ["golpear", "pegar"] ],
    [ ["hold"], ["held"], ["held"], ["sujetar"] ],
    [ ["hurt"], ["hurt"], ["hurt"], ["herir", "doler", "hacer daño"] ],
    [ ["keep"], ["kept"], ["kept"], ["guardar", "mantener"] ],
    [ ["know"], ["knew"], ["known"], ["saber", "conocer"] ],
    [ ["lay"], ["laid"], ["laid"], ["poner", "extender"] ],
    [ ["lead"], ["led"], ["led"], ["guiar", "conducir"] ],
    [ ["learn"], ["learnt", "learned"], ["learnt", "learned"], ["aprender"] ],
    [ ["leave"], ["left"], ["left"], ["dejar", "irse", "salir"] ],
    [ ["lend"], ["lent"], ["lent"], ["prestar"] ],
    [ ["let"], ["let"], ["let"], ["permitir", "dejar"] ],
    [ ["lie"], ["lay"], ["lain"], ["tumbarse", "echarse"] ],
    [ ["lie"], ["lied"], ["lied"], ["mentir"] ],
    [ ["light"], ["lit"], ["lit"], ["encender"] ],
    [ ["lose"], ["lost"], ["lost"], ["perder"] ],
    [ ["make"], ["made"], ["made"], ["hacer", "fabricar"] ],
    [ ["mean"], ["meant"], ["meant"], ["significar", "querer decir"] ],
    [ ["meet"], ["met"], ["met"], ["conocer( a)", "quedar( con)"] ],
    [ ["pay"], ["paid"], ["paid"], ["pagar"] ],
    [ ["put"], ["put"], ["put"], ["poner"] ],
    [ ["read"], ["read"], ["read"], ["leer"] ],
    [ ["ride"], ["rode"], ["ridden"], ["montar"] ],
    [ ["ring"], ["rang"], ["rung"], ["llamar( por teléfono)"] ],
    [ ["rise"], ["rose"], ["risen"], ["elevarse", "alzarse"] ],
    [ ["run"], ["ran"], ["run"], ["correr"] ],
    [ ["say"], ["said"], ["said"], ["decir"] ],
    [ ["see"], ["saw"], ["seen"], ["ver"] ],
    [ ["sell"], ["sold"], ["sold"], ["vender"] ],
    [ ["send"], ["sent"], ["sent"], ["enviar"] ],
    [ ["set"], ["set"], ["set"], ["colocar"] ],
    [ ["shake"], ["shook"], ["shaken"], ["agitar"] ],
    [ ["shine"], ["shone"], ["shone"], ["brillar"] ],
    [ ["shoot"], ["shot"], ["shot"], ["disparar"] ],
    [ ["show"], ["showed"], ["shown"], ["enseñar", "mostrar"] ],
    [ ["shut"], ["shut"], ["shut"], ["cerrar"] ],
    [ ["sing"], ["sang"], ["sung"], ["cantar"] ],
    [ ["sink"], ["sank"], ["sunk"], ["hundirse"] ],
    [ ["sit"], ["sat"], ["sat"], ["sentarse"] ],
    [ ["sleep"], ["slept"], ["slept"], ["dormir"] ],
    [ ["smell"], ["smelt", "smelled"], ["smelt", "smelled"], ["oler"] ],
    [ ["speak"], ["spoke"], ["spoken"], ["hablar"] ],
    [ ["spell"], ["spelt", "spelled"], ["spelt", "spelled"], ["deletrear"] ],
    [ ["spend"], ["spent"], ["spent"], ["gastar", "pasar tiempo"] ],
    [ ["stand"], ["stood"], ["stood"], ["estar de pie"] ],
    [ ["steal"], ["stole"], ["stolen"], ["robar"] ],
    [ ["stick"], ["stuck"], ["stuck"], ["pegar"] ],
    [ ["sweep"], ["swept"], ["swept"], ["barrer"] ],
    [ ["swin"], ["swan"], ["swun"], ["nadar"] ],
    [ ["take"], ["took"], ["taken"], ["coger", "llevar"] ],
    [ ["teach"], ["taught"], ["taught"], ["enseñar"] ],
    [ ["tear"], ["tore"], ["torn"], ["romper", "desgarrar"] ],
    [ ["tell"], ["told"], ["told"], ["decir", "contar"] ],
    [ ["think"], ["thought"], ["thought"], ["pensar"] ],
    [ ["throw"], ["threw"], ["thrown"], ["lanzar", "tirar"] ],
    [ ["understand"], ["understood"], ["understood"], ["comprender", "entender"] ],
    [ ["wake up"], ["woke up"], ["woken up"], ["despertar(se)"] ],
    [ ["wear"], ["wore"], ["worn"], ["llevar puesto", "ponerse"] ],
    [ ["win"], ["won"], ["won"], ["ganar"] ],
    [ ["write"], ["wrote"], ["written"], ["escribir"] ],
];